name: Stage

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: frontend
            context: ./frontend
            tag: "dofus/frontend"
          - name: backend
            context: ./backend
            tag: "dofus/backend"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push ${{ matrix.service.name }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.service.context }}
        push: true
        tags: ${{ matrix.service.tag }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

